name: drkwon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_markdown: ^0.7.6+2
  flutter_quill: ^11.1.0
  flutter_quill_extensions: ^11.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0-beta.4
  font_awesome_flutter: ^10.8.0
  go_router: ^14.7.2
  http: ^1.3.0
  image_picker: ^1.1.2
  js: ^0.7.1
  jwt_decoder: ^2.0.1
  logger: ^2.5.0 
  quill_native_bridge: ^11.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  video_player: ^2.9.3
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/htmls/
    - assets/data_files/
