name: drkwon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  intl: ^0.20.2
  js: ^0.7.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/htmls/
    - assets/data_files/
